-- Ejercicio 1
CREATE OR REPLACE FUNCTION es_jefe (v_id IN HR.EPLOYEES.EMPLOYEE_ID%TYPE) RETURN BOOLEAN 
IS 
v_count NUMBER;

BEGIN
	SELECT COUNT(*) INTO v_count
	FROM HR.EMPLOYEES E
	WHERE E.MANAGER_ID == v_id;

	IF v_count > 0 THEN
		DBMS_OUTPUT.PUT_LINE('Es manager')
	ELSE
		DBMS_OUTPUT.PUT_LINE('No es manager')
	END IF;
END;

-- Ejercicio 2
CREATE OR REPLACE FUNCTION salario_con_bonus(e_id IN HR.EMPLOYEES.EMPLOYEE_ID%TYPE) RETURN NUMBER 
IS 

BEGIN


END;
