CREATE OR REPLACE TRIGGER t_nuevoE
BEFORE INSERT ON HR_EMPLOYEES

BEGIN
	IF :NEW.SALARY < 1000 THEN
		RAISE_APPLICATION_ERROR(-20001, 'Rácano');
	END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_1
BEFORE DELETE ON HR_EMPLOYEES
FOR EACH ROW
BEIGN
	IF :OLD.DEPARTMENT_ID = 90 THEN
		RAISE_APPLICATION_ERROR(-20001, 'not');
	END IF;
END;
/

-- Ejercicio 6
CREATE OR REPLACE TRIGGER trg_mod 
BEFORE UPDATE ON HR_EMPLOYEES
BEGIN
	IF :OLD.EMPLOYEE_ID < 105 THEN
		RAISE_APPLICATION_ERROR(-20001, 'noooo');
	END IF;
END;
/

-- Ejercicio 9
CREATE OR REPLACE TRIGGER trg_2
BEFORE INSERT OR UPDATE ON HR_JOBS
FOR EACH ROW
BEGIN
	IF :OLD.JOB_ID LIKE 'IT_PROG' AND :NEW.SALARY > 8000 THEN
		RAISE_APPLICATION_ERROR(-20001, 'demasiao caro');
	END IF;
END;
/
